### ISSUE TITLE
[bug?] The polybar module seems to have some performance issues 

### ISSUE THREAD

**Issue by nichroot** [gabrielzschmitz/Tomato.C#56]
I don't know if it's just on my system, but like even without starting tomato the cpu usage when I log into the desktop bumps to the 20-30 % territory, like normally it's always below 5 even when browsing on the web and watching videos with loads of tabs open. Please do check if it's happening on your system too, thanks!

**Comment by gabrielzschmitz** [comment]
This isn't intentional, but it may be caused by repeatedly opening and closing the time log file. I'm currently working on a new version of Tomato.C, rebuilding it from the ground up with a cleaner codebase and more modular features, including improved logging. I appreciate your patience during this time. Thank you, and I apologize for any inconvenience.

**Comment by nichroot** [comment]
thanks for the reply, take your time! 🤜🏻
